[2023-03-21 01:29:47,955] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_oetker_app.run_data_metrics manual__2023-03-21T01:29:34.992044+00:00 [queued]>
[2023-03-21 01:29:47,966] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_oetker_app.run_data_metrics manual__2023-03-21T01:29:34.992044+00:00 [queued]>
[2023-03-21 01:29:47,967] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 01:29:47,967] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-21 01:29:47,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 01:29:47,981] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_data_metrics> on 2023-03-21 01:29:34.992044+00:00
[2023-03-21 01:29:47,986] {standard_task_runner.py:52} INFO - Started process 1353 to run task
[2023-03-21 01:29:47,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_oetker_app', 'run_data_metrics', 'manual__2023-03-21T01:29:34.992044+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_oetker_app.py', '--cfg-path', '/tmp/tmp8br258wk', '--error-file', '/tmp/tmpu1386yk_']
[2023-03-21 01:29:47,991] {standard_task_runner.py:80} INFO - Job 13: Subtask run_data_metrics
[2023-03-21 01:29:48,054] {task_command.py:369} INFO - Running <TaskInstance: dag_oetker_app.run_data_metrics manual__2023-03-21T01:29:34.992044+00:00 [running]> on host ec81750b2a36
[2023-03-21 01:29:48,147] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=julia
AIRFLOW_CTX_DAG_ID=dag_oetker_app
AIRFLOW_CTX_TASK_ID=run_data_metrics
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T01:29:34.992044+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T01:29:34.992044+00:00
[2023-03-21 01:30:00,579] {logging_mixin.py:115} INFO - --------------------------------------------------------------------------------------------------
[2023-03-21 01:30:00,580] {logging_mixin.py:115} INFO - Unique users: 1000
[2023-03-21 01:30:00,581] {logging_mixin.py:115} INFO - Most represented country: China with 202 users
[2023-03-21 01:30:00,582] {logging_mixin.py:115} INFO - Least represented country: Paraguay with 1 users
[2023-03-21 01:30:00,582] {logging_mixin.py:115} INFO - --------------------------------------------------------------------------------------------------
[2023-03-21 01:30:00,586] {python.py:173} INFO - Done. Returned value was: None
[2023-03-21 01:30:00,608] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_oetker_app, task_id=run_data_metrics, execution_date=20230321T012934, start_date=20230321T012947, end_date=20230321T013000
[2023-03-21 01:30:00,663] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-21 01:30:00,710] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
